export const services = [
	{
		category: 'Additions & Remodels',
		services: [
			'Additions',
			'Bathroom Remodel',
			'Basement Remodel',
			'Kitchen Remodel',
			'Garage Remodel',
			'Major Renovation - Multiple Rooms',
			'Minor Remodels',
			'Outbuildings & Structures',
			'Recovery Services - Disaster',
			'Site Preparation',
			'Specialty - Disability, Chairlifts, Elevators',
			'Swimming Pool - Remodel',
		],
	},
	{
		category: 'Air Conditioning & Cooling',
		services: [
			'Central Air Conditioning - Install',
			'Central Air Conditioning - Repair or Service',
			'Fans',
			'Swamp Cooler - Install or Replace',
			'Window A/C Unit - Install',
			'Outdoor Mist Cooling System - Install',
			'Outdoor Mist Cooling System - Repair',
			'Refrigeration System - Install or Replace',
			'Refrigeration System - Repair or Service',
			'Swamp Cooler - Service or Repair',
			'Window A/C Unit - Service or Relocate',
		],
	},
	{
		category: 'Architects, Builders & Engineers',
		services: [
			'Architects',
			'Builders (New Home)',
			'Engineers',
			'General Contractors',
			'Land Surveyor',
			'Construction Manager',
			'Developer',
			'Draftsperson / CADD',
			'Permit Service',
		],
	},
	{
		category: 'Bathroom Remodeling',
		services: [
			'Bathroom Remodeling & Design',
			'Cabinets & Countertops',
			'Painting & Staining',
			'Plumbing',
			'Tile',
			'Electrical',
			'Flooring',
			'Glass & Mirrors',
			'Hot Tubs & Spas',
			'Walls & Ceilings',
			'Windows & Doors',
		],
	},
	{
		category: 'Carpentry & Woodworking',
		services: [
			'Cabinets & Countertops',
			'Decks, Fences & Ramps',
			'Doors',
			'Finish Carpentry, Trim & Molding',
			'Framing',
			'Closets',
			'Outbuildings, Sheds & Gazebos',
			'Stairs & Railings',
			'Siding, Gutters & Exterior Trim',
		],
	},
	{
		category: 'Cabinets',
		services: [
			'Cabinets - Install',
			'Cabinets - Reface',
			'Custom Cabinets or Built-In Furniture',
			'Cabinets - Refinish',
			'Countertops',
			'Cabinets - Repair',
			'Closet - Build',
			'Closets or Rooms - Organize',
			'Garage Organizers - Install',
		],
	},
	{
		category: 'Cleaning Services',
		services: [
			'Maid Service',
			'Carpet & Draperies',
			'Windows',
			'Exterior Home',
			'Interior Home',
			'Property Cleanup',
			'Ducts & Vents - Clean',
			'Chimney & Fireplace - Clean',
			'Post-Construction Cleanup',
			'Waste Material & Junk Removal',
		],
	},
	{
		category: 'Concrete, Brick & Stone',
		services: [
			'Driveways & Floors',
			'Patios, Walks & Steps',
			'Chimney, Fireplace, Stove & Barbecue',
			'Foundations',
			'Siding - Brick, Stone, or Stucco',
			'Tile & Countertops',
			'Waterproofing & Drywells',
			'Other Concrete Services',
			'Walls',
		],
	},
	{
		category: 'Countertops',
		services: [
			'Ceramic & Porcelain Tile - Install',
			'Stone Slab (Granite, Quartz, etc.) - Install',
			'Laminate Countertops - Install',
			'Solid Surface (Corian, Concrete, etc.) - Install',
			'Natural Stone Tile - Install',
			'Tile, Stone, Grout - Clean',
			'Ceramic & Porcelain Tile - Repair',
			'Stone Slab (Granite, Quartz, etc.) - Repair',
			'Laminate Countertops - Repair',
			'Solid Surface (Corian, Concrete, etc.) - Repair',
			'Natural Stone Tile - Repair',
		],
	},
	{
		category: 'Decorators & Designers',
		services: [
			'Designer - Kitchen',
			'Designer - Building',
			'Interior Decorator',
			'Designer - Landscape',
			'Designer - Residential (Interior Space Planner)',
			'Consultant - Professional Home or Office Organizer',
			'Designer - Bathroom',
			'Designer - Feng Shui',
			'Designer - Interior Lighting Plan',
			'Designer - Window Treatments',
			'Disability Planner',
		],
	},
	{
		category: 'Drywall & Insulation',
		services: [
			'Drywall - Install',
			'Drywall - Repair',
			'Batt, Rolled & Reflective Insulation',
			'Blown-In Insulation',
			'Soundproofing',
			'Spray Foam Insulation',
		],
	},
	{
		category: 'Decks, Porches & Patios',
		services: [
			'Build a Deck or Porch',
			'Build a Patio',
			'Clean & Seal a Deck or Porch',
			'Build an Arbor, Pergola, or Trellis',
			'Build a Gazebo',
			'Repair a Deck or Porch',
			'Repair a Gazebo',
			'Install Outdoor Play Equipment',
			'Repair Outdoor Play Equipment',
		],
	},
	{
		category: 'Electrical & Computers',
		services: [
			'Outlets, Panels, Switches & Wiring',
			'Cables, Networks & Telephones',
			'Electronics, Computers & Home Media Systems',
			'Appliances',
			'Fans',
			'Generators',
			'Heating & Thermostats',
			'Home Security & Alarms',
			'Lighting Design',
		],
	},
	{
		category: 'Energy Efficiency',
		services: [
			'Energy Efficient Home Heating',
			'Home Insulation & Weatherstripping',
			'Home Solar Energy',
			'Energy Efficient Windows & Doors',
			'Home Energy Audit',
			'Energy Efficient Appliances',
			'Geothermal Energy',
		],
	},
	{
		category: 'Fences',
		services: [
			'Wood Fence - Install',
			'Vinyl or PVC Fence - Install',
			'Chain Link Fence - Install',
			'Wrought Iron Fence - Install',
			'Aluminum or Steel Fence - Install',
			'Aluminum or Steel Fence - Repair',
			'Barbed Wire Fence - Install',
			'Barbed Wire Fence - Repair',
			'Chain Link Fence - Repair or Alter',
			'Gate for Driveway or Security - Install or Replace',
			'Vinyl or PVC Fence - Repair',
			'Wood Fence - Repair',
			'Wrought Iron Fence - Repair or Weld',
		],
	},
	{
		category: 'Flooring',
		services: [
			'Brick & Stone',
			'Carpet',
			'Hardwood',
			'Laminate & Vinyl',
			'Tile',
			'Concrete',
			'Sports Surfaces (Tennis, Courts and Synthetic Grass)',
		],
	},
	{
		category: 'Foundations',
		services: [
			'Concrete Foundation - Install',
			'Concrete Foundation - Repair or Raise',
			'Foundation Drainage - Install or Replace',
			'Foundation or Basement - Waterproofing',
		],
	},
	{
		category: 'Garage',
		services: [
			'Garage - Build',
			'Garage - Remodel',
			'Garage Door - Install or Replace',
			'Garage Door Opener - Install',
			'Garage Organizers - Install',
			'Garage Door - Repair',
			'Garage Door Opener - Repair or Adjust',
			'Waste Material & Junk Removal',
		],
	},
	{
		category: 'Green Home Improvement Projects',
		services: [
			'Home Solar Energy',
			'Energy Efficient Windows & Doors',
			'Home Insulation & Weatherstripping',
			'Energy Efficient Appliances',
			'Energy Efficient Home Heating',
			'Home Energy Audit',
			'Home/Roof Skylights',
			'Geothermal Energy',
		],
	},
	{
		category: 'Handyman Services',
		services: [
			'Carpentry',
			'Gutters',
			'Handyman for Multiple Small Projects',
			'Painting, Staining & Drywall',
			'Electrical',
			'Plumbing & Sprinklers',
			'Other Handyman Services',
		],
	},
	{
		category: 'Heating & Furnaces',
		services: [
			'Boilers & Radiators',
			'Central Heating Systems',
			'Electric Wall & Radiant Heat Systems',
			'Fans',
			'Water Heaters',
			'Ducts & Vents',
			'Fireplaces, Inserts, Stoves & Barbecues',
			'Fuel Delivery & Storage',
			'Insulation',
			'Thermostats & Accessories',
			'Other HVAC Types',
		],
	},
	{
		category: 'Home Construction',
		services: [
			'Additions',
			'Major Remodels & Renovations',
			'New Home Construction',
			'Outbuildings & Structures',
			'Site Preparation',
		],
	},
	{
		category: 'Home Inspectors & Appraisers',
		services: [
			'Appraisal - Real Estate',
			'Appraisal - General',
			'Home Inspector',
			'Inspection - Roofing',
			'Inspection - Waterproofing',
		],
	},
	{
		category: 'Home Theater',
		services: [
			' Home Theater System or Media Center - Install',
			'Home Automation - Install or Service',
			'Home Theater Surround Sound System - Insall',
			'Install, Repair or Conceal Home Theater Wiring',
			'TV Wall Mount',
			'Antenna',
			'Electronic Drape, Shade or Blind Opener - Install',
			'Home Theater Accessory',
			'Home Theater System or Media Center - Repair',
			'Satellite Dish System',
			'Universal Remote Control Consolidation & Programming',
			'Satellite Dish - Install',
			'Satellite Dish - Repair',
		],
	},
	{
		category: 'Home Winterization',
		services: [
			'Home Insulation & Weatherstripping',
			'Energy Efficient Home Heating',
			'Energy Efficient Windows & Doors',
			'Chimney or Fireplace - Clean and Inspect',
			'Winterize Roofing/Gutters',
			'Winterize Lawn/Landscape',
			'Home Energy Audit',
			'Gutters & Downspouts - Clean',
			'Snow Removal',
		],
	},
	{
		category: 'Household Chores',
		services: [
			'Furniture Assembly',
			'Packing & Unpacking Services',
			'Lifting & Moving Heavy Items',
			'Box Recycling & Disposal',
			'Yard & Garden Work',
			'Toys & Games Assembly',
			'Outdoor Equipment & Furniture Assembly',
		],
	},
	{
		category: 'Moving & Storage',
		services: [
			'Painting & Staining',
			'Professional Moving Services',
			'Storage',
			'Waste Material & Junk Removal',
			'Consultants & Move-Related Professionals',
			'Home Security & Alarms',
			'Cleaning Services',
			'Wiring, Cabling, and Telephones',
			'Appraisers & Home Inspectors',
		],
	},
	{
		category: 'Kitchen Remodeling',
		services: [
			'Kitchen Remodeling & Design',
			'Cabinets & Countertops',
			'Painting & Staining',
			'Plumbing',
			'Tile',
			'Appliances',
			'Electrical',
			'Flooring',
			'Walls & Ceilings',
			'Windows & Doors',
		],
	},
	{
		category: 'Landscape, Yard & Garden',
		services: [
			'Landscaping - Design & Installation',
			'Landscaping - Maintenance of Lawn & Trees',
			'Landscaping - Sprinkler Systems',
			'Pools & Water Features',
			'Tree & Shrub Service',
			'Decks, Porches, Gazebos & Play Equipment',
			'Fences',
			'Outdoor Patios, Steps & Walkways',
			'Outdoor Walls & Retaining Walls',
		],
	},
	{
		category: 'Painting & Staining',
		services: [
			'Exterior Painting or Staining',
			'Interior Painting or Staining',
			'Special Finishes',
			'Paint Preparation',
			'Paint Removal and Cleaning',
			'Decorators & Designers',
			'Wallpapering',
		],
	},
	{
		category: 'Plumbing',
		services: [
			'Drain Clearing',
			'Faucets, Fixtures & Pipes',
			'Septic Systems, Sewers & Water Mains',
			'Sprinkler Systems',
			'Water Heaters',
			'Boilers & Radiators',
			'Hot Tubs & Spas',
			'Pumps',
			'Water Softening & Purification',
			'Other Plumbing Related Jobs',
		],
	},
	{
		category: 'Roofing',
		services: [
			'Roofing - Install or Replace',
			'Roofing - Repair',
			'Roofing & Gutters - Clean',
			'Gutters',
			'Skylights',
			'Inspection - Roofing',
			'Heating Cable for Roof - Install',
			'Sealant for Roof - Apply',
			'Metal Roofing - Paint',
		],
	},
	{
		category: 'Siding',
		services: [
			'Vinyl Siding - Install',
			'Vinyl Siding - Repair',
			'Wood or Fiber Cement - Install',
			'Metal Siding - Install',
			'Traditional Stucco - Install',
			'Asbestos Siding - Repair',
			'Brick or Stone Siding - Install',
			'Brick or Stone Siding - Repair',
			'Exterior Trim - Install',
			'Exterior Trim - Repair',
			'Metal Siding - Repair',
			'Spray-on Siding - Apply',
			'Synthetic Stucco Siding - Install',
			'Synthetic Stucco Siding - Repair',
			'Traditional Stucco Siding - Repair',
			'Wood or Fiber Cement - Repair',
		],
	},
	{
		category: 'Swimming Pools, Spas, Hot Tubs & Saunas',
		services: [
			'Gazebos & Enclosures',
			'Hot Tubs & Spas',
			'Saunas',
			'Swimming Pool Decks & Patios',
			'Swimming Pools',
		],
	},
	{
		category: 'Tile & Stone',
		services: [
			'Tile: Ceramic & Porcelain - Install',
			'Tile: Natural Stone - Install',
			'Pavers for Driveways & Floors - Install',
			'Brick & Stone for Patios - Install',
			'Tile, Stone, Grout - Clean',
			'Pavers for Patios, Walks & Steps - Install',
			'Tile: Ceramic & Porcelain - Repair',
			'Tile: Natural Stone - Repair',
			'Brick & Stone for Patios - Repair',
		],
	},
	{
		category: 'Walls & Ceilings',
		services: [
			'Painting & Texturing',
			'Carpentry - Trim Work & Framing',
			'Ceilings',
			'Ceilings - Fans',
			'Drywall & Insulation',
			'Cleaning',
			'Tile',
			'Wallcoverings',
			'Walls - Exterior',
			'Walls - Interior',
		],
	},
	{
		category: 'Windows & Doors',
		services: [
			'Windows - Installation & Repair',
			'Doors - Garage, Sliding, Glass, etc.',
			'Hardware, Locks & Screens',
			'Windows - Cleaning',
			'Windows - Treatments',
			'Glass & Mirrors',
			'Awnings & Patio Covers',
			'Windows - Protection & Tinting',
		],
	},
	{
		category: 'Other Services',
		services: [
			'Environmental (Asbestos, Lead, Mold, and Radon Gas)',
			'Fireplaces, Inserts, Stoves, and Barbecues',
			'Furniture',
			'Home Security',
			'Metal Work, Blacksmiths and Signmakers',
			'Pest Control (Birds, Insects, Rodents, Termites)',
			'Recovery Services (Water, Fire, etc)',
			'Removal of Junk or Building Materials',
			'Water Softening & Purification',
		],
	},
];
